[build]
  command = "react-scripts build"
  functions = "netlify/functions"
  publish = "build"

  ## Redirect for create-react-app
  [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

  ## Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## More info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
